Added my YuvrajSingh.md to Readmes
Design-and-Code/Dope-Github-Readmes pull request #45
Opened 2021-10-30 16:16 UTC by Yuvraj883

2021-10-31 02:03 UTC, Panquesito7 requested changes

2021-10-31 02:03 UTC, Panquesito7 commented on Readmes/YuvrajSingh.md
> +📫 How to reach me:
```suggestion
📫 How to reach me
```

2021-10-31 02:03 UTC, Panquesito7 commented on Readmes/YuvrajSingh.md
> + ### Show some ❤️ by starring some of the repositories!
```suggestion
### Show some ❤️ by starring some of the repositories!
```

2021-10-31 02:03 UTC, Panquesito7 commented on Readmes/YuvrajSingh.md
> +  <img src="https://profile-counter.glitch.me/Mohasin-Haque/count.svg" />
I recommend removing the visitor count badge as it's inaccurate.

2021-11-08 13:31 UTC, Greeshma2903 commented
Hey @Yuvraj883, please let us know if you want to make the changes requested. We'll be able to go ahead with the merge then.

2021-11-16 10:42 UTC, Greeshma2903 commented
Closing #45 due to inactivity

2021-11-16 10:42 UTC, closed without merging