Create README.md
Design-and-Code/Dope-Github-Readmes pull request #46
Opened 2021-11-07 01:12 UTC by frankiefab100

Add `@frankiefab100` Github README file.

2021-11-07 01:59 UTC, Panquesito7 requested changes

2021-11-07 01:59 UTC, Panquesito7 commented on Readmes/Franklin Ohaegbulam/README.md
> +<p align="left"> <img src="https://komarev.com/ghpvc/?username=frankiefab100&label=Profile%20views&color=0e75b6&style=flat" alt="frankiefab100" /> </p>
I recommend removing the profile views badge as it's inaccurate.
```suggestion
```

2021-11-07 01:59 UTC, Panquesito7 commented on Readmes/Franklin Ohaegbulam/README.md
> +- 💬 Feel free to reach out: DM [@frankiefab100](https://twitter.com/frankiefab100)
```suggestion
- 💬 Feel free to reach me out at my Twitter: [@frankiefab100](https://twitter.com/frankiefab100)
```

2021-11-07 01:59 UTC, Panquesito7 commented on Readmes/Franklin Ohaegbulam/README.md
> +<h3 align="left"> Let's Connect:</h3>
```suggestion
<h3 align="left"> Let's Connect</h3>
```

2021-11-07 01:59 UTC, Panquesito7 commented on Readmes/Franklin Ohaegbulam/README.md
> +<h3 align="left">Languages and Tools:</h3>
```suggestion
<h3 align="left">Languages and Tools</h3>
```

2021-11-07 16:38 UTC, frankiefab100 commented
Alright

2021-11-07 16:47 UTC, Panquesito7 reviewed
There are still some of my suggestions above not being applied. If you don't want them, however, please let me know. 🙂

2021-11-08 13:04 UTC, frankiefab100 commented
@Panquesito7 I hope I got it right this time?🙂

2021-11-08 13:29 UTC, Greeshma2903 commented
This looks great @frankiefab100, going ahead with the merge 🚀

2021-11-08 13:29 UTC, merged

2021-11-08 18:11 UTC, Panquesito7 reviewed
LGTM! 🚀