add my readme
Design-and-Code/Dope-Github-Readmes pull request #47
Opened 2021-11-08 16:20 UTC by sudip-mondal-2002

2021-11-08 18:40 UTC, Panquesito7 requested changes
Awesome readme! 🚀
These are all some suggestions by the Markdown linter. 🙂

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +# Sudip Mondal
```suggestion
# Sudip Mondal

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +## Skills
```suggestion
## Skills

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +### Personal Projects
```suggestion
### Personal Projects

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +### Group projects
```suggestion
### Group projects

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +### Project under Professors
```suggestion
### Project under Professors

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +## Professional Experiences
```suggestion
## Professional Experiences

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +## Position of Responsibilities
```suggestion
## Position of Responsibilities

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +## Co-curricular Activities
```suggestion
## Co-curricular Activities

```

2021-11-08 18:40 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +## Scholastic Achievements
```suggestion
## Scholastic Achievements

```

2021-11-08 19:07 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +[E-mail](mailto:sudipmondal.2002@rediffmail.com) | [LinkedIn](https://www.linkedin.com/in/sudip-mondal-374a12201/) | [Facebook](https://www.facebook.com/sudip16022002/) | [Instagram](https://www.inst
```suggestion
[E-mail](mailto:sudipmondal.2002@rediffmail.com) | [LinkedIn](https://www.linkedin.com/in/sudip-mondal-374a12201/) | [Facebook](https://www.facebook.com/sudip16022002/) | [Instagram](https://www.instagram.com/sudip._.mondal/) | [Twitter](https://twitter.com/SUDIPMO19931261) | [YouTube](https://www.youtube.com/channel/UCvfY9VkXaFNxQJO7lfDV6Vw) | [GitHub](https://github.com/sudip-mondal-2002) | [Website](https://sudipmondal.tk) | [NPM](https://www.npmjs.com/~sudipmondal) | [PyPI](https://pypi.org/user/sudip-mondal-2002/)

```

2021-11-08 19:22 UTC, Panquesito7 commented on Readmes/Sudip Mondal/README.md
> +   * Worked as Subject Matter Expert for mathematics.
```suggestion
   * Worked as Subject Matter Expert for mathematics.

```

2021-11-09 18:52 UTC, Panquesito7 approved these changes
LGTM! 🚀

2021-11-09 19:15 UTC, sudip-mondal-2002 commented
How to get it merged?

2021-11-09 19:44 UTC, Panquesito7 commented
> How to get it merged?

A maintainer has to merge it. I'm not a maintainer, so I can't merge it. 😅

2021-11-10 01:14 UTC, DevrajDC approved these changes
Looks good, merging it 🚀

2021-11-10 01:14 UTC, merged