Added my readme file
Design-and-Code/Dope-Github-Readmes pull request #62
Opened 2022-08-19 17:28 UTC by MahendraBishnoi29

2022-08-19 18:31 UTC, Panquesito7 commented on Readmes/Mahendra/README.md
> +- 📫 How to reach me **mahendrabishnoi4488@gmail.com**
```suggestion
- 📫 How to reach me: **mahendrabishnoi4488@gmail.com**
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Inelegant

2022-08-19 18:31 UTC, Panquesito7 commented on Readmes/Mahendra/README.md
> +# 📊GitHub Stats :
```suggestion
# 📊GitHub Stats
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Inelegant

2022-08-21 16:34 UTC, Panquesito7 requested changes

2022-08-21 16:34 UTC, Panquesito7 commented on Readmes/Mahendra/README.md
> +![](https://komarev.com/ghpvc/?username=MahendraBishnoi29&label=Visitors+Count&color=brightgreen)
Remove the profile count badge, as it's inaccurate.
```suggestion
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-21 18:49 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-25 13:39 UTC, MahendraBishnoi29 commented
Hey @Panquesito7 it's not merged yet is anything wrong with my PR ?

2022-08-25 14:35 UTC, Greeshma2903 approved these changes

2022-08-25 14:36 UTC, merged