Vedant profile added
Design-and-Code/Dope-Github-Readmes pull request #67
Opened 2023-01-18 17:37 UTC by vedantpople4

2023-01-18 18:18 UTC, Panquesito7 requested changes
Good readme! 🚀

2023-01-18 18:18 UTC, Panquesito7 commented on Readmes/Vedant-Pople/README.md
> +
There's an extra line here.
```suggestion
```

2023-01-18 18:18 UTC, Panquesito7 commented on Readmes/Vedant-Pople/README.md
> +## ❤ Views and Followers
```suggestion
## ❤ Views and Followers

```

2023-01-18 18:18 UTC, Panquesito7 commented on Readmes/Vedant-Pople/README.md
> +## 🚀 Languages and Tools:
I recommend removing the `:` here. What do you think?

```suggestion
## 🚀 Languages and Tools
```

2023-01-18 18:18 UTC, Panquesito7 commented on Readmes/Vedant-Pople/README.md
> +## Connect with me:
I recommend removing the `:` here. What do you think?
```suggestion
## Connect with me

```

2023-01-22 06:13 UTC, vedantpople4 commented on Readmes/Vedant-Pople/README.md
> +
Done

2023-01-22 07:04 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-22 12:28 UTC, Greeshma2903 approved these changes

2023-01-22 12:28 UTC, merged

2023-01-22 12:28 UTC, Greeshma2903 commented
Thank you for contributing! 💯